### ISSUE TITLE
象鼻虫、放大镜和注能铁放在水面上没有使用正确的动画/不会下沉

### ISSUE THREAD

**Issue by Cassielu123** [DST-Hamlet/PorkLand#141]
象鼻虫壳（armor_weevole）和放大镜（magnifyling_glass）没有使用放置于水面的动画。
注能铁块（infused_iron）不会下沉。

**Comment by Ziwbi** [comment]
armor_weevole 没有水上动画 应该下沉

**Comment by Ziwbi** [comment]
已在 Ziwbi/misc_items 分支修复
