### ISSUE TITLE
店主在黄昏或者晚上后离开桌子就不会再试图坐回去

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#190]

**Comment by Legend-Master** [comment]
Can't reproduce

![image](https://github.com/user-attachments/assets/d5112801-6ce6-435f-9c6a-512c7d91e55d)
![image](https://github.com/user-attachments/assets/76c3f91f-4666-46d1-9ddc-7c00c17eebb4)
![image](https://github.com/user-attachments/assets/58a103df-4e78-4f70-a794-a52abc22f7a2)
