### ISSUE TITLE
在身上没有呼噜币的时候购买猪伯利学会的呼噜币会导致游戏卡死，不崩溃也没有报错

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#212]

**Comment by Legend-Master** [comment]
Can't reproduce

![image](https://github.com/user-attachments/assets/f5e655fc-e51c-42aa-926d-a2cf134cfd07)

**Comment by Noctice** [comment]
> Can't reproduce
> 
> ![image](https://private-user-images.githubusercontent.com/68118705/357694113-646d6a2f-6d89-4734-b270-22115c7d807b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzAyNTEsIm5iZiI6MTcyMzYyOTk1MSwicGF0aCI6Ii82ODExODcwNS8zNTc2OTQxMTMtNjQ2ZDZhMmYtNmQ4OS00NzM0LWIyNzAtMjIxMTVjN2Q4MDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEwMDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OGY1MmI0ZWI3NTZjZTdiMjkxMjQ2ZTRlYTNlOTY0YjQ5NjgyYTk2ZTQ3MzI2NTU3NjI0MTdiNDkzZGY2NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zuzj2snB9mJyhUBTHMlLHZyqZy4CTQe85eUC9kq91SM)

应该是和https://github.com/DST-Hamlet/PorkLand/issues/211是同一个底层bug引起，所以在211号issue修复后这个bug也被修复
