### ISSUE TITLE
毒腺不能吃

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#264]

**Comment by Jerry457** [comment]
能吃吧，只有中毒了才能吃我记得

**Comment by Noctice** [comment]
> 能吃吧，只有中毒了才能吃我记得

目前在mod里中毒之后触发的是解毒剂的动作

**Comment by Jerry457** [comment]
毒腺就是这样设计的

**Comment by Noctice** [comment]
我敢肯定单机版不中毒也可以吞毒腺
![image](https://github.com/user-attachments/assets/2cac16fe-94a7-4fa5-b923-2f4293faa732)

**Comment by Jerry457** [comment]
> 我敢肯定单机版不中毒也可以吞毒腺 ![image](https://private-user-images.githubusercontent.com/47233045/358648583-2cac16fe-94a7-4fa5-b923-2f4293faa732.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjU4NDUsIm5iZiI6MTcyMzgyNTU0NSwicGF0aCI6Ii80NzIzMzA0NS8zNTg2NDg1ODMtMmNhYzE2ZmUtOTRhNy00ZmE1LWI5MjMtMmY0MjkzZmFhNzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE2MjU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNThiMDU3YjhiYjA2MGIzNGI0YzEzMmZjNzk0YmJmNDQxZmMzNDNjZWVkOTRkM2U1OWY0ZmRkMTAyN2JkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ru04lLxqBo3kqzzxV2U2SCsg3dkE7ihqP8OfNMtP4FE)

但是动作是是跳起来

**Comment by Noctice** [comment]
而且我们mod里人物吃毒腺的动作也有问题，应该用吃素食的前摇动作，我们的前摇太短了

**Comment by Noctice** [comment]
> > 我敢肯定单机版不中毒也可以吞毒腺 ![image](https://private-user-images.githubusercontent.com/47233045/358648583-2cac16fe-94a7-4fa5-b923-2f4293faa732.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjU4NDUsIm5iZiI6MTcyMzgyNTU0NSwicGF0aCI6Ii80NzIzMzA0NS8zNTg2NDg1ODMtMmNhYzE2ZmUtOTRhNy00ZmE1LWI5MjMtMmY0MjkzZmFhNzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE2MjU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNThiMDU3YjhiYjA2MGIzNGI0YzEzMmZjNzk0YmJmNDQxZmMzNDNjZWVkOTRkM2U1OWY0ZmRkMTAyN2JkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ru04lLxqBo3kqzzxV2U2SCsg3dkE7ihqP8OfNMtP4FE)
> 
> 但是动作是是跳起来

这个确实是跳起来

**Comment by Noctice** [comment]
吃毒腺的动作名字也缺少汉化
