### ISSUE TITLE
商店商品需要补全

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#282]
缺少的商店物品列表：

- [x] fabric布
- [x] antivenom解毒剂
- [x] sweet_potato甜薯（建议删除）
- [x] coconut椰子（建议删除）
- [x] bamboo竹子
- [x] ox_horn水牛角
- [x] cutlass剑鱼刀
- [x] coconade椰子炸弹
- [x] captainhat船长帽（建议删除）

商店蓝图及缺少的对应制品：

- [x] ox_flute_blueprint降雨排箫蓝图    降雨排箫
- [x] trawlnet_blueprint拖网蓝图    拖网及沉水物品打捞机制

其他建议删除的商店货物：

- [x] pinecone松果

一些无关但是可以顺便做的内容：

- [x] 布的制作配方，只能从蓝图获得（哈姆雷特遗迹罐子掉布蓝图的概率特别大）

**Comment by KUV233** [comment]
松果能不删吗，饥荒单机原版就有，我还靠他砍树
