### ISSUE TITLE
洞穴开启后，在室内行走会播放错误的地皮音效

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#428]

**Comment by Ziwbi** [comment]
回响也是这样吗

**Comment by Noctice** [comment]
> 回响也是这样吗

回音似乎没有被正确设置，我在蝙蝠洞里听起来和default差不多，然后输入TheWorld.components.pl_ambientsound:SetReverbPreset("batcave")后才明显有蝙蝠洞的回音效果

**Comment by Noctice** [comment]
刚刚又测试了一下，客机其实完全不播放在地皮上行走的音效，也完全不会改变室内回音效果。

**Comment by Ziwbi** [comment]
客机没有房间定义啊，，，
