### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by Cassielu123** [DST-Hamlet/PorkLand#456]
反馈群中 “傻逼基友（顺从）” （2949762887）的反馈
请问这是怎么回事，mod只开了哈姆和t台
没有开地下
![f27a502b5598afe0d5b3b8b60429556d](https://github.com/user-attachments/assets/c398b7b2-5b91-417e-b765-5e1cb524410f)
[client_log.txt](https://github.com/user-attachments/files/16755988/client_log.txt)

**Comment by xiaomizhouwei** [comment]
这好像是微软运行库的锅，正常饥荒崩溃不是会弹出来一个界面吗
