### ISSUE TITLE
疑似不老泉/摇摇欲坠柱子的崩溃

### ISSUE THREAD

**Issue by Cassielu123** [DST-Hamlet/PorkLand#520]
来自JKJK32 （QQ2819367467）
不知道啊，我走到大蛇泉旁边就崩了。
然后再进还是崩。
[client_log (1).txt](https://github.com/user-attachments/files/16824741/client_log.1.txt)

**Comment by Noctice** [comment]
> 来自JKJK32 （QQ2819367467） 不知道啊，我走到大蛇泉旁边就崩了。 然后再进还是崩。 [client_log (1).txt](https://github.com/user-attachments/files/16824741/client_log.1.txt)

是“Insight BOSS倒计时功能加强”这个mod的问题，与above the clouds无关
