### ISSUE TITLE
猪人守卫的戟不会像单机一样因为猪人守卫打人掉耐久

### ISSUE THREAD

**Issue by swarm1984** [DST-Hamlet/PorkLand#525]
### What happened?

单机ham里猪人守卫掉落的戟会因为猪人原先a到了多少次而掉相应的耐久，而mod里无论猪人砍了我好几下掉落出来的戟依然是100%耐久

**Comment by Legend-Master** [comment]
单机就是不会掉耐久的，但是因为有 bug 保存重新进就会掉耐久了

**Comment by swarm1984** [comment]
> 单机就是不会掉耐久的，但是因为有 bug 保存重新进就会掉耐久了

所以按照单机版的设定确实也是不会掉耐久的？昨天测试的时候还真遇到过但是之后没复现出来

**Comment by Legend-Master** [comment]
是，但是说实话单机大量的东西保存重进都会有 bug，有些东西重进之后出现的问题反倒是变成更常见更合理的行为了
