### ISSUE TITLE
雨林树烧焦后没有对应的小地图图标，雨林树和爪棕榈树砍伐时不会概率额外掉落一个木炭

### ISSUE THREAD

**Issue by swarm1984** [DST-Hamlet/PorkLand#543]
### What happened?

包括雨林树（正常，毒气雨林中生病，蜘蛛猩猩结网），茶树，爪棕榈树

**Comment by Ziwbi** [comment]
单机的树烧焦后不会自己掉落木炭

**Comment by swarm1984** [comment]
> 单机的树烧焦后不会自己掉落木炭

我刚才试了会掉

**Comment by swarm1984** [comment]
补充一下块茎树也会在烧完之后概率掉出一个木炭

**Comment by Noctice** [comment]
修了砍伐不掉额外木炭，另一个我觉得可以算是working as intended
