### ISSUE TITLE
My feedback and a few questions/features.

### ISSUE THREAD

**Issue by xKli0x** [DST-Hamlet/PorkLand#554]
### What is missing?

1. Do you plan to add Hamlet (+Wagstaff) characters to the game in the future? If not, can you take a look at the compatibility of the "Hamlet Characters -Fixed and Reporked" mod? This mod is pretty solidly made, but it only works when I don't turn on the caves, and turning them off kills my fps in the game.

2. Will you add BFB (roc bird)?

3. The pig guards should also defend the turfs that I dig in the city.

4. Large amounts of tall grass in one place cause huge lag, which could possibly be fixed if there was an option in the mod settings to turn off its animation (although I'm not sure).

5. I would like to ask you to add an option in the mod settings that will allow you to increase the amount of bosses health.

Thank you for creating the wonderful port of Hamlet!

Best regards,
Exel

**Comment by Ziwbi** [comment]
1. Yes there will be Hamlet characters
2. Yes, it's WIP
345. Needs discussion

**Comment by Legend-Master** [comment]
> Do you plan to add Hamlet (+Wagstaff) characters to the game in the future? If not, can you take a look at the compatibility of the "Hamlet Characters -Fixed and Reporked" mod? This mod is pretty solidly made, but it only works when I don't turn on the caves, and turning them off kills my fps in the game.

We do have a plan but we don't have the time to do it yet, we'll track this in #481

> Will you add BFB (roc bird)?

This is added now

> The pig guards should also defend the turfs that I dig in the city.

After some discussion, we don't quite agree on this

> Large amounts of tall grass in one place cause huge lag, which could possibly be fixed if there was an option in the mod settings to turn off its animation (although I'm not sure).

This will be tracked in #698

> I would like to ask you to add an option in the mod settings that will allow you to increase the amount of bosses health.

We don't plan to do it at the moment, might revisit this once we got all other higher priority things done and got more time work on this
