### ISSUE TITLE
Characters from other mods have some of their announcement quotes replaced with Wilson's

### ISSUE THREAD

**Issue by Cameoflage** [DST-Hamlet/PorkLand#559]
### What happened?

I was playing Walani from the Shipwrecked Characters mod and I noticed that her quotes for being in the dark, coming out of the dark, and announcing that she was hungry showed up as Wilson's rather than either Walani's quotes from singleplayer or the quotes that were included in the Shipwrecked Characters mod. This probably happens with all modded characters but I've only had Walani players on my server so far. Walani did have her normal quotes for Hamlet-specific announcements, like vampire bat attacks and going in and out of humid season fog clouds.

**Comment by Noctice** [comment]
working as intended
