### ISSUE TITLE
Hanging Vines knock out all inventory items instead of just food

### ISSUE THREAD

**Issue by Cameoflage** [DST-Hamlet/PorkLand#560]
### What is missing?

In the most recent patch for single player Don't Starve, hanging vines were changed to knock the first edible item out of your inventory instead of the first item of any kind like they did at release. (This isn't very important, just a minor inconsistency; I would add the 'low priority' label but I can't find it. I only joined github about an hour ago so I'm still figuring this stuff out.)

**Comment by Noctice** [comment]
Perhaps this is also not bad
