### ISSUE TITLE
暂时发现的几处

### ISSUE THREAD

**Issue by newwbeeee** [DST-Hamlet/PorkLand#566]
### What happened?

- [ ] 完全敲塌柱子产生的大地震并不能波及其他房间，再加上武器店还未添加椰子炸弹，让前期很难探索隐藏房间。
- [x] 调好日晷后遗迹的鬼魂不消失。
- [x] 先驱召唤技能初始cd为0（一上来就召唤）。另外不知道是不是故意改的，一是先驱对影怪没伤害，二是召唤的青蛙雨有点像老版的，没有延迟且从玩家四面八方来
- [ ] 内部仍然会有黄昏夜晚的降san光环
- [x] 漩涡斗篷能抵挡影怪攻击。且头盔不能分摊耐久
- [x] 在船上不能使用蚊子血囊，但蜘蛛腺可以

可能是故意改的：不能像联机一样用火把敲东西，更不能像单机一样黑暗中敲

**Comment by Noctice** [comment]
> ### What happened?
> 1.完全敲塌柱子产生的大地震并不能波及其他房间，再加上武器店还未添加椰子炸弹，让前期很难探索隐藏房间。 2.调好日晷后遗迹的鬼魂不消失。 3.先驱召唤技能初始cd为0（一上来就召唤）。另外不知道是不是故意改的，一是先驱对影怪没伤害，二是召唤的青蛙雨有点像老版的，没有延迟且从玩家四面八方来 4.内部仍然会有黄昏夜晚的降san光环 5.漩涡斗篷能抵挡影怪攻击。且头盔不能分摊耐久 5.在船上不能使用蚊子血囊，但蜘蛛腺可以 6.可能是故意改的：不能像联机一样用火把敲东西，更不能像单机一样黑暗中敲
> 
> ### Relevant log output
> _No response_

1、这个特性准备和蚁穴一起更新
6、火把敲东西这个我不清楚，但是我特意写了可以连续敲黑暗中的东西，只要你用鼠标拖动工具敲

**Comment by newwbeeee** [comment]
> > ### What happened?
> > 1.完全敲塌柱子产生的大地震并不能波及其他房间，再加上武器店还未添加椰子炸弹，让前期很难探索隐藏房间。 2.调好日晷后遗迹的鬼魂不消失。 3.先驱召唤技能初始cd为0（一上来就召唤）。另外不知道是不是故意改的，一是先驱对影怪没伤害，二是召唤的青蛙雨有点像老版的，没有延迟且从玩家四面八方来 4.内部仍然会有黄昏夜晚的降san光环 5.漩涡斗篷能抵挡影怪攻击。且头盔不能分摊耐久 5.在船上不能使用蚊子血囊，但蜘蛛腺可以 6.可能是故意改的：不能像联机一样用火把敲东西，更不能像单机一样黑暗中敲
> > ### Relevant log output
> > _No response_
> 
> 1、这个特性准备和蚁穴一起更新 6、火把敲东西这个我不清楚，但是我特意写了可以连续敲黑暗中的东西，只要你用鼠标拖动工具敲

鼠标拖动工具敲具体怎么操作的？我用鼠标拖动工具到柱子并长按只能敲一下，连续按和按空格也不行

**Comment by Legend-Master** [comment]
> 完全敲塌柱子产生的大地震并不能波及其他房间，再加上武器店还未添加椰子炸弹，让前期很难探索隐藏房间。

我们会在 #408 继续跟踪

> 内部仍然会有黄昏夜晚的降san光环

单独开了一个新 issue 来追踪 #728
