### ISSUE TITLE
使用活性机甲左键被摧毁的商店会导致服务器崩溃

### ISSUE THREAD

**Issue by MoEPlayer-china** [DST-Hamlet/PorkLand#581]
### What happened?

[00:06:10]: [string "../mods/workshop-3315075550/main/actions.lu..."]:283: attempt to index field 'door' (a nil value)
LUA ERROR stack traceback:
    ../mods/workshop-3315075550/main/actions.lua:283 in (field) fn (Lua) <281-287>
    scripts/bufferedaction.lua:26 in (method) Do (Lua) <22-36>
    scripts/entityscript.lua:1552 in (method) PerformBufferedAction (Lua) <1534-1567>
    ../mods/workshop-3315075550/postinit/stategraphs/SGwilson.lua:1700 in () ? (Lua) <1699-1703>
    =(tail call):-1 in ()  (tail) <-1--1>
    scripts/stategraph.lua:465 in (method) HandleEvent (Lua) <463-471>
    scripts/stategraph.lua:479 in (method) HandleEvents (Lua) <473-488>
    scripts/stategraph.lua:154 in (method) UpdateEvents (Lua) <148-157>
    scripts/stategraph.lua:145 in (method) Update (Lua) <109-146>
    scripts/update.lua:288 in () ? (Lua) <224-298>

**Comment by Ziwbi** [comment]
beta版已停止维护 请使用[正式版](https://steamcommunity.com/sharedfiles/filedetails/?id=3322803908)
