### ISSUE TITLE
Feedback - Reap What you Sow farming mechanics and skill tree mechanics

### ISSUE THREAD

**Issue by YellowCaoMoo** [DST-Hamlet/PorkLand#594]
### What is missing?

Although using the old farms is more faithful to Hamlet, I'd at least like the option to use the new farming mechanics added in Reap what you Sow, as the new overhauled farming mechanics are more fun an engaging than the legacy ones.

Furthermore, Wilson lost his skill tree stuff. I'm assuming that isn't a bug, and it was done intentionally to be faithful to Hamlet. Again, the stuff added in each characters' skill trees make them more fun, and It would be appreciated if I at least had the option to enable it in the mod.

**Comment by Ziwbi** [comment]
intended change
