### ISSUE TITLE
放大镜，遗迹入口，大鸟

### ISSUE THREAD

**Issue by maybewow** [DST-Hamlet/PorkLand#597]
### What is missing?

放大镜不能辨别遗迹裂缝，鳞片遗迹入口无法通往蛇岛，四十多天了大鸟没有来

**Comment by Noctice** [comment]
1、放大镜问题在开发版本已修复，将在下个更新中解决
2、请发送存档，目前我的所有测试存档鳞片遗迹都可以到达蛇岛
3、大鸟目前是待做事项
