### ISSUE TITLE
非主机玩家无法出房间

### ISSUE THREAD

**Issue by dls01011** [DST-Hamlet/PorkLand#598]
### What happened?

我和朋友联机买了房产，进去之后我（房主）能出去但我朋友出不去了

**Comment by Noctice** [comment]
> ### What happened?
> 我和朋友联机买了房产，进去之后我（房主）能出去但我朋友出不去了
> 
> ### Relevant log output
> _No response_

这个问题将在明天的更新中修复，目前你们可以尝试使用空格交互键与门互动
