### ISSUE TITLE
仅开启了[时崎狂三]和本mod导致的崩溃

### ISSUE THREAD

**Issue by SanXiQiong** [DST-Hamlet/PorkLand#614]
### What happened?

![QQ图片20240910175222](https://github.com/user-attachments/assets/cc4769cf-cd68-49d7-af33-2bcf920140a2)
如图

**Comment by SanXiQiong** [comment]
[00:04:07]: Disabling workshop-3322803908 (云霄国度-Above the Clouds) because it had an error.	
[00:04:07]: [string "../mods/workshop-3322803908/main/toolutil.l..."]:20: bad argument #2 to '_debug_setupvalue' (number expected, got nil)
LUA ERROR stack traceback:
        =[C] in function '_debug_setupvalue'
        ../mods/workshop-3322803908/main/toolutil.lua(20,1) in function 'setupvalue'
        ../mods/workshop-3322803908/main/toolutil.lua(59,1) in function 'SetUpvalue'
        ../mods/workshop-3322803908/postinit/stategraphs/SGwilson.lua(2409,1)
        =(tail call) ?
        =[C] in function 'xpcall'
        scripts/mods.lua(187,1) in function 'modfn'
        scripts/stategraph.lua(323,1) in function '_ctor'
        scripts/class.lua(191,1)
        =(tail call) ?
        =[C] in function '?'
        ../mods/workshop-2941989744/modmain.lua(1,1) in function '_require'
        ../mods/workshop-3322803908/main/postinit.lua(167,1) in function 'require'
        scripts/entityscript.lua(64,1) in function 'LoadStateGraph'
        scripts/entityscript.lua(1064,1) in function '?'
        scripts/prefabs/player_common.lua(2588,1) in function 'fn'
        scripts/mainfunctions.lua(336,1)
[00:04:07]: [string "../mods/workshop-3322803908/main/toolutil.l..."]:20: bad argument #2 to '_debug_setupvalue' (number expected, got nil)
LUA ERROR stack traceback:
        =[C] in function '_debug_setupvalue'
        ../mods/workshop-3322803908/main/toolutil.lua(20,1) in function 'setupvalue'
        ../mods/workshop-3322803908/main/toolutil.lua(59,1) in function 'SetUpvalue'
        ../mods/workshop-3322803908/postinit/stategraphs/SGwilson.lua(2409,1)
        =(tail call) ?
        =[C] in function 'xpcall'
        scripts/mods.lua(187,1) in function 'modfn'
        scripts/stategraph.lua(323,1) in function '_ctor'
        scripts/class.lua(191,1)
        =(tail call) ?
        =[C] in function '?'
        ../mods/workshop-2941989744/modmain.lua(1,1) in function '_require'
        ../mods/workshop-3322803908/main/postinit.lua(167,1) in function 'require'
        scripts/entityscript.lua(64,1) in function 'LoadStateGraph'
        scripts/entityscript.lua(1064,1) in function '?'
        scripts/prefabs/player_common.lua(2588,1) in function 'fn'
        scripts/mainfunctions.lua(336,1)

**Comment by xiaomizhouwei** [comment]
目前该制作组暂未有兼容其他mod的想法，只能让mod作者兼容本mod
