### ISSUE TITLE
新建而没去过的房间不会在地图上显示箭头

### ISSUE THREAD

**Issue by Cassielu123** [DST-Hamlet/PorkLand#616]
### What happened?

新建而没去过的房间不会在地图上显示箭头

### Relevant log output

```text
新建而没去过的房间不会在地图上显示箭头
```

**Comment by Legend-Master** [comment]
![image](https://github.com/user-attachments/assets/6750e5f5-c4e1-4d50-9de3-55212be2a21c)
![image](https://github.com/user-attachments/assets/c7c0a4ed-ddac-42a0-8192-e22db6d9c53c)
