### ISSUE TITLE
在遗迹里回档会导致在遗迹里面的人无法与门交互（鼠标指着门没有反应）（遗迹外的人不受影响）

### ISSUE THREAD

**Issue by TCKGXJfish** [DST-Hamlet/PorkLand#628]
### What happened?
发生了什么？

在洞穴或遗迹外存档  进洞穴或遗迹回档  会导致这个问题

### Relevant log output
相关的日志

_No response_

**Comment by Noctice** [comment]
无法复现
请确保安装了最新版本的above the clouds
https://steamcommunity.com/sharedfiles/filedetails/?id=3322803908
