### ISSUE TITLE
玩家拆除房屋和房屋门机制改动

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#634]
在单机版，如果在玩家拆除了一扇门或拆除了一个房间之后，会导致该玩家无法到达房屋出口，那么这扇门或这个房间就不能被拆除
在我们mod中，应当改为：如果在玩家拆除了一扇门或拆除了一个房间之后，会导致从房屋出口出发无法到达所有房间，那么这扇门或这个房间就不能被拆除

**Comment by Legend-Master** [comment]
Implemented in c824c9a314f451bcaa9b6df4bd0a52c298b1d113
