### ISSUE TITLE
玩家拆除房间机制改动

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#635]
在单机版，如果在玩家拆除了一个房间之后，会导致该玩家无法到达房屋出口，那么这个房间就不能被拆除
在我们mod中，应当改为：如果在玩家拆除了一个房间之后，会导致从房屋出口出发无法到达所有房间，那么这个房间就不能被拆除

**Comment by Legend-Master** [comment]
Tracked in #634
