### ISSUE TITLE
正对房子入口的位置不应当能造门

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#646]
### What happened?
发生了什么？

![image](https://github.com/user-attachments/assets/f3d86d71-19df-4c9b-9c80-44071e5f7057)

### Relevant log output
相关的日志

_No response_

**Comment by Legend-Master** [comment]
Fixed in #4fec29d7c2e132cc1af5a4c7ea7f6a79ae2f8b56
