### ISSUE TITLE
玩着玩着突然崩了，错误追踪mod报的云霄

### ISSUE THREAD

**Issue by Sakura211314** [DST-Hamlet/PorkLand#670]
### What happened? 发生了什么？

开了武器成长；额外物品mod；Cherry Fores这个几个大型mod；t剩下的就是80格大冰箱；大背包；持久挖矿；更好的随从，五根琉璃；自动浇水之类的。
崩之前正常完了大半天，不知道啥原因

**Comment by Noctice** [comment]
有日志么？

**Comment by 3242394814** [comment]
开这么多Mod不崩才怪😕
