### ISSUE TITLE
哈姆雷特版的辣蔬菜鸡尾酒没有名字、地面贴图、烹饪锅贴图

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#678]
### What happened? 发生了什么？

哈姆雷特版的辣蔬菜鸡尾酒没有名字、地面贴图、烹饪锅贴图

**Comment by Cassielu123** [comment]
我觉得我们应该删了它然后改DST的蔬菜鸡尾酒

**Comment by Legend-Master** [comment]
Fixed in 92ef23161739d1cfb16f0c95f869cdeb87d4e70e
