### ISSUE TITLE
开局无猪人面具；雷帽不防雷

### ISSUE THREAD

**Issue by zifeng-kang** [DST-Hamlet/PorkLand#687]
### What is missing?

蜘蛛人，小恶魔和鱼妹开局不给猪人面具；
雷帽不防雷

**Comment by Legend-Master** [comment]
雷帽我测试确实是防雷的，给猪人面具的问题鱼人不会主动被猪打，其他俩有待讨论

**Comment by Legend-Master** [comment]
merging with #558
