### ISSUE TITLE
出于未知原因，在我的存档的某个位置进行走动会导致帧率明显下降

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#692]
### What happened? 发生了什么？

出于未知原因，在我的存档的某个位置进行走动会导致帧率明显下降

https://github.com/user-attachments/assets/d7325b0f-b1d5-4750-a24d-fdc7981524bd
[Cluster_113.zip](https://github.com/user-attachments/files/17183006/Cluster_113.zip)

我在会出现问题的位置放置了一个紫色月眼

**Comment by Noctice** [comment]
应该是蝙蝠导致的卡顿，我T了10个蝙蝠就卡得要死，T其他生物就不会

**Comment by Ziwbi** [comment]
蝙蝠真的很奇怪 完全看不出来哪里导致的卡顿
