### ISSUE TITLE
露比蛋会因为bug卡消失

### ISSUE THREAD

**Issue by Noctice** [DST-Hamlet/PorkLand#737]
### What happened? 发生了什么？

露比蛋无法在容器中完成孵化，然而当一个孵化进度100%的露比蛋从容器中的一个格子转移到另一个格子时，则可以完成孵化，此时将露比蛋继续移动格子，则可以取消砂囊石的生成。

**Comment by Legend-Master** [comment]
Fixed in 8bcee1cc47c0c183c74703e8831e470f2e239686
