### ISSUE TITLE
联机时随从生物会被滞留在上一个房间，只有队友也进去之后随从生物才出现在了房间内

### ISSUE THREAD

**Issue by iiYuuki** [DST-Hamlet/PorkLand#745]
### What happened? 发生了什么？

联机：双人联机。
人物：我选温蒂，同时召唤了阿比盖尔以及雇佣了两只猪人。猪人是我雇佣的，不是队友
场景：任何地洞房间。
操作：我先行进入另一个房间。过一会队友再进来
现象：我进入房间后，阿比盖尔和猪人同时滞留在了队友的画面内乱窜。等到队友进来之后，阿比盖尔和猪人才一起进来

**Comment by Legend-Master** [comment]
这个问题已经在 #717 里有人汇报了，我们会在那边继续跟踪
