### ISSUE TITLE
Crash upon lightning strike

### ISSUE THREAD

**Issue by Dr-Ratticus** [DST-Hamlet/PorkLand#749]
### What happened? 发生了什么？

Game crashed when one of the bird thingies tried to hit me with lightning 
![image](https://github.com/user-attachments/assets/f58ed31d-dca1-490c-a4dc-d5dc31abf0b3)

**Comment by Legend-Master** [comment]
Seems like something related to missing `isexternallyinsulated` on player's inventory component, I don't think we changed anything about it though, I'm guessing it's a bug in some of the other mods you enabled, can you still reproduce this with all other mods disabled?

**Comment by Legend-Master** [comment]
I'll close this for now since I can't reproduce the crash and there's no response for a month, feel free to re-open this if it's still happening for you

**Comment by Noctice** [comment]
45 inventory slot causes this crash
