### ISSUE TITLE
玩家的房子与商店在某些情况下产生与光有关的bug

### ISSUE THREAD

**Issue by KUV233** [DST-Hamlet/PorkLand#769]
### What happened? 发生了什么？

可能是在房子装修后，所有房子，包括商店都变得十分黑，可以出查理那种黑，房子自带的增san光环都阻挡不了掉san。

### Relevant log output 相关的日志

```text
nope
```

**Comment by KUV233** [comment]
正常情况下，房屋内即便没有灯，也不会有查理，san也可以增加；
现在是房屋内没等就会被查理打，san框框地下降，灯的范围看起来也很小。

**Comment by Noctice** [comment]
请问能发送存档或者截图吗？

**Comment by KUV233** [comment]
[Uploading Cluster_42.zip…]()

**Comment by KUV233** [comment]
[Uploading Cluster_42.zip…]()

**Comment by KUV233** [comment]
![Uploading 20241118100647_1.jpg…]()

**Comment by KUV233** [comment]
![20241118100659_1](https://github.com/user-attachments/assets/99b20aa7-4e5b-4441-937b-f223522cb807)
![20241118100703_1](https://github.com/user-attachments/assets/c39e212d-b325-44cf-a62c-9feb622c39d1)
![20241118100647_1](https://github.com/user-attachments/assets/895a79a9-b52b-4caa-b26b-c61edb6608bd)
![20241118100655_1](https://github.com/user-attachments/assets/0b9efc1b-a45a-46f5-a9db-df988b6bc382)

**Comment by KUV233** [comment]
[Cluster_42.zip](https://github.com/user-attachments/files/17793581/Cluster_42.zip)

**Comment by Noctice** [comment]
好的，收到，我们会在近期研究这个问题

**Comment by Noctice** [comment]
请问是否开启过云霄过度补丁mod？如果开启过，那么可能是云霄过度补丁mod导致了该问题。
想要修复现有存档，在出现问题的室内中心生成一个deco_roomglow实体即可。（注意最好不要在同一个室内生成多次）

**Comment by KUV233** [comment]
开启过。由于该补丁产生bug还麻烦你们，抱歉。
