### ISSUE TITLE
进入/离开猪人的商店时可能会利用身上的物品制作其他物品，导致进入/离开猪人的商店的这一交互失败

### ISSUE THREAD

**Issue by yizhilurenjia** [DST-Hamlet/PorkLand#774]
### What happened? 发生了什么？

进入/离开猪人的商店时可能会利用身上的物品制作其他物品，就比如身上有足够木头时与猪人商店房进行交互会导致制作木板，并且无法进入/离开猪人商店房，直到身上无可制作的物品

**Comment by Noctice** [comment]
请问能提供屏幕录像吗？

**Comment by Noctice** [comment]
已复现，属于饥荒联机版本体问题，因其涉及到游戏底层代码，目前不予修复。
复现流程：在跳虫洞前连续点击两下制作键，第二下点击直到屏幕变黑时再松开鼠标，并且保持鼠标的位置一直在制作按键上方，即可复现
