### ISSUE TITLE
虫群不会被其他光亮吸引

### ISSUE THREAD

**Issue by kbqak47** [DST-Hamlet/PorkLand#775]
### What happened? 发生了什么？

被虫群附身后，在黄昏或者夜晚，不会被雷鸟或者猪镇的路灯所吸引从而离开玩家，会一直附身，与单机版哈姆雷特里的虫群不一样。

**Comment by Noctice** [comment]
请问能提供录像吗？我测试时并没有这个问题

**Comment by kbqak47** [comment]
发现问题所在了，开了“武器成长”这个模组就会出现上述问题，关闭该模组就恢复原样。

**Comment by kbqak47** [comment]
> 发现问题所在了，开了“武器成长”这个模组就会出现上述问题，关闭该模组就恢复原样。
