### ISSUE TITLE
Server crashes when shadow monster spawns.

### ISSUE THREAD

**Issue by Gorthok1** [DST-Hamlet/PorkLand#779]
### What happened? 发生了什么？

When a shadow monster (Crawling Horror, terrorbeak) spawns either from insanity or the Ancient Herald, the server and your game immediately crashes and if rejoining after an Ancient Herald spawned shadows, the game will be locked onto the loading screen unless the server is rolled back. An easy way to reproduce it is to type into the command console: (C_spawn"terrorbeak") or (C_spawn"crawlinghorror") without the parenthesis.

### Relevant log output 相关的日志

```text
[string "../mods/workshop-3322803908/postinit/prefab..."]:14: attempt to index field 'locomotor' (a nil value) LUA ERROR stack traceback:
../mods/workshop-3322803908/postinit/prefabs/shadowcreature.lua(14,1)
=(tail call) ?
=[C] in function 'xpcall'
scripts/mods.lua(188,1) in function 'mod'
scripts/mainfunctions.lua(345,1)
```

**Comment by Noctice** [comment]
fixed
