### ISSUE TITLE
出猪镇商店崩溃

### ISSUE THREAD

**Issue by Queen-Yao** [DST-Hamlet/PorkLand#784]
### What happened? 发生了什么？

出猪镇商店崩溃

### Relevant log output 相关的日志

```text
COROUTINE 172177 SCRIPT CRASH:
[string "../mods/workshop-3322803908/postinit/compon..."]:25: attempt to index local '_activeplayers' (a nil value)
LUA ERROR stack traceback:
        ../mods/workshop-3322803908/postinit/components/kramped.lua(25,1) in function 'ForceOnNaughtyAction'
        ../mods/workshop-3322803908/postinit/prefabs/player.lua(135,1) in function 'fn'
        scripts/entityscript.lua(1215,1) in function '_PushEvent'
        ../mods/workshop-3322803908/postinit/entityscript.lua(105,1) in function 'PushEvent'
        ../mods/workshop-3322803908/scripts/components/interiorvisitor.lua(364,1) in function 'UpdateExteriorPos'
        ../mods/workshop-3322803908/scripts/components/door.lua(75,1)	
[00:05:16]:
```

**Comment by Noctice** [comment]
根据日志来看，这极有可能是与另一个修改了坎普斯机制的mod发生了mod冲突，并非本mod自身问题导致的崩溃

**Comment by Queen-Yao** [comment]
我想，代码需要进一步判定，来防止这个错误发生，提高兼容性

**Comment by Noctice** [comment]
> 我想，代码需要进一步判定，来防止这个错误发生，提高兼容性

不幸地是，该mod功能仅能使用hook写法来实现，而想要提高这一写法的兼容性，则必须由双方均修改代码来保证稳定性。而如果有第三个mod出现了该冲突，那么三方均需要修改代码才能保证兼容。这在开发流程中是几乎不可能实现的。

**Comment by Queen-Yao** [comment]
我推荐判定为 if _activeplayers and _activeplayers[player] then 而非 if  _activeplayers[player] then 这可以使得这个报错被消除

**Comment by Queen-Yao** [comment]
这既提高了兼容性，还不会影响代码本身的运行。

**Comment by Noctice** [comment]
> 我推荐判定为 if _activeplayers and _activeplayers[player] then 而非 if _activeplayers[player] then 这可以使得这个报错被消除

但是这样mod功能就无法实现，而日后如果mod存在需要依赖此功能的功能，那么就会导致新的问题。如果可以，请您提供完整的日志，以找出产生冲突的mod，或许我们可以找到别的兼容方案。

**Comment by Queen-Yao** [comment]
根据报错，您的函数 ToolUtil.GetUpvalue(self.OnUpdate, "_activeplayers") 在没有成功获取到 _activeplayers 的本地函数，我想不是有什么修改了坎普斯 .而是我们的 debug 函数出现了互相冲突 感谢解答，现在 此问题 已被解决。
